
import "./globals.css";
import { ThemeProvider } from "../component/theme_provider";
import {Inter} from "next/font/google";
import { ThemeToggle } from "@/component/theme_toggle";
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full" >
      <body className={inter.className}>

        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
         
          <div className="flex flex-col h-full">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
